export const heroCat = [
  "Lifestyle",
  "Travel",
  "Food",
  "Fashion",
  "Health & Fitness",
  "Technology",
  "Personal Development",
  "Finance",
  "DIY & Crafts",
  "Beauty",
  "Parenting",
  "Home & Garden",
  "Education",
  "Photography",
  "Entertainment",
  "Business & Entrepreneurship",
  "Sports",
  "Music",
  "Automotive",
  "Book Reviews",
];
